### ISSUE TITLE
Timer1 registers have the wrong size

### ISSUE THREAD

**Issue by cculpepper** [riscv-rust/gd32vf103-pac#3]
https://github.com/riscv-rust/gd32vf103-pac/blob/d98f791d2d4a39253b7b55182c147d56252563c0/src/timer1.rs#L281

I could be wrong about this, but it looks like timer 1 has the wrong size for the capture registers. They are set as u32, but the user manual and the svd have them as u16. The user manual does say these can be accessed as 32 bit words, so if my issue is in error, let me know.

**Comment by Disasm** [comment]
For some reason in SVD it's defined as 16-bit for TIMER0 and as 32-bit for TIMER1. I don't think it matters. Generated code looks correct to me.

**Comment by Disasm** [comment]
Since CHxCV and DMATB registers are the only 32-bit-declared ones in TIMER1, they could be patched, but I don't think it's necessary unless you have strong feelings about it.

**Comment by cculpepper** [comment]
Nope, no strong feelings. Just thought it odd, and wanted to make sure I wasn't going crazy.
